apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: shimmy-simple
  annotations:
    scenarios.ai.sap.com/description: "Simple Shimmy inference server - binary only, no model baking"
    scenarios.ai.sap.com/name: "shimmy-simple"
    executables.ai.sap.com/description: "Direct Shimmy binary without proxy wrapper - minimal deployment"
    executables.ai.sap.com/name: "shimmy-simple"
  labels:
    scenarios.ai.sap.com/id: "shimmy-simple"
    ai.sap.com/version: "1.0.0"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: infer.s
    spec: |
      predictor:
        imagePullSecrets:
        - name: ollamadocker
        minReplicas: 1
        maxReplicas: 3
        containers:
        - name: kserve-container
          image: docker.io/gjkarthik/shimmy:latest
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
            - name: SHIMMY_PORT
              value: "8080"
            - name: SHIMMY_HOME
              value: "/opt/shimmy"
            - name: MODEL_PATH
              value: "/models"
          volumeMounts:
          - name: models
            mountPath: /models
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
        volumes:
        - name: models
          emptyDir: {}
