apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: shimmy-rbac-fix
  annotations:
    scenarios.ai.sap.com/description: "Shimmy with Istio bypass - no RBAC enforcement"
    scenarios.ai.sap.com/name: "shimmy-rbac-fix"
    executables.ai.sap.com/description: "Shimmy inference service with Istio port exclusion to bypass RBAC"
    executables.ai.sap.com/name: "shimmy-rbac-fix"
  labels:
    scenarios.ai.sap.com/id: "shimmy-rbac-fix"
    ai.sap.com/version: "1.0.1"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
        sidecar.istio.io/rewriteAppHTTPProbers: true
        traffic.sidecar.istio.io/excludeInboundPorts: 8080
      labels: |
        ai.sap.com/resourcePlan: infer.s
    spec: |
      predictor:
        imagePullSecrets:
          - name: ollamadocker
        minReplicas: 1
        maxReplicas: 1
        containers:
          - name: kserve-container
            image: docker.io/gjkarthik/shimmy:rbac-fix
            ports:
              - containerPort: 8080
                protocol: TCP
            env:
              - name: SHIMMY_PORT
                value: "8080"
              - name: SHIMMY_MODEL_PATH
                value: "/models"
            volumeMounts:
              - name: models
                mountPath: /models
            resources:
              requests:
                memory: "512Mi"
                cpu: "500m"
              limits:
                memory: "2Gi"
                cpu: "1000m"
            livenessProbe:
              tcpSocket:
                port: 8080
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
            readinessProbe:
              tcpSocket:
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 5
              timeoutSeconds: 3
              failureThreshold: 3
        volumes:
          - name: models
            emptyDir: {}
