apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: shimmy-lightweight
  annotations:
    scenarios.ai.sap.com/description: "Lightweight Shimmy inference server with GPU support - models loaded at runtime"
    scenarios.ai.sap.com/name: "shimmy-lightweight"
    executables.ai.sap.com/description: "Shimmy inference service without baked models - fast deployment with GPU"
    executables.ai.sap.com/name: "shimmy-lightweight"
  labels:
    scenarios.ai.sap.com/id: "shimmy-lightweight"
    ai.sap.com/version: "2.0.0"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: infer.m
    spec: |
      predictor:
        imagePullSecrets:
        - name: ollamadocker
        minReplicas: 1
        maxReplicas: 3
        containers:
        - name: kserve-container
          image: docker.io/gjkarthik/shimmy:lightweight
          ports:
          - containerPort: 8000
            name: http1
            protocol: TCP
          env:
            - name: SHIMMY_PORT
              value: "8080"
            - name: SHIMMY_HOST
              value: "0.0.0.0"
            - name: SHIMMY_BASE_GGUF
              value: "/models"
          volumeMounts:
          - name: models
            mountPath: /models
          resources:
            requests:
              memory: "4Gi"
              cpu: "2000m"
              nvidia.com/gpu: "1"
            limits:
              memory: "8Gi"
              cpu: "4000m"
              nvidia.com/gpu: "1"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 18
        volumes:
        - name: models
          emptyDir: {}
          # To use PVC for persistent models, uncomment below and comment emptyDir:
          # persistentVolumeClaim:
          #   claimName: shimmy-models-pvc
