apiVersion: v1
kind: Service
metadata:
  name: shimmy-model-downloader
  namespace: kube-scb
  labels:
    app: shimmy-model-downloader
spec:
  type: ClusterIP
  selector:
    app: shimmy-model-downloader
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
